name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: get release
      run: |
       wget https://github.com/Tkiliay/android_device_xiaomi_grus/releases/download/Stable/Cherish-OS-v4.3-20230102-0855-grus-UNOFFICIAL-GApps.zip >>> 1.txt
       unzip Cherish-OS-v4.3-20230102-0855-grus-UNOFFICIAL-GApps.zip
       ls
       wget https://github.com/danielmmmm/dat2img/raw/master/sdat2img.py
       pip install brotli
       brotli -d system.new.dat.br
       python sdat2img.py system.transfer.list system.new.dat system.img

    - name: Release
      uses: softprops/action-gh-release
      with:
        files:  /home/runner/work/test/test/system.img
        fail_on_unmatched_files: true
